# Basic Information 
title: Lixuan He | 何立轩
position: Undergraduate Student
affiliation: Tsinghua University
email: helx23@mails.tsinghua.edu.cn

# Search Engine Optimization (SEO)
keywords: Lixuan He, Reinforcement Learning, Natural Language Processing, Representation Learning, Computer Vision
description: Lixuan He's personal homepage at Tsinghua University.
canonical: https://TSYJ-He.github.io/

# Links 
google_scholar: https://scholar.google.com/citations?hl=zh-CN&user=yMq5pA8AAAAJ
cv_link: assets/files/curriculum_vitae.pdf
github_link: https://github.com/TSYJ-He
twitter: https://x.com/lixuan_thu?s=21 

# Images
avatar: ./assets/img/avatar.png # 你的头像图片路径
favicon: ./assets/img/favicon.png # 浏览器标签页的小图标
favicon_dark: ./assets/img/favicon-dark.png # 暗黑模式下的小图标

# Footnote
enable_footnote: true

# Auto Dark Mode
# 设置为 false 来禁用暗黑模式，以匹配 knightnemo 的风格
auto_dark_mode: false

# Font
font: "Serif" # 你可以保持 "Serif" 或改为 "Sans Serif"

# Jekyll 配置
remote_theme: yaoyao-liu/minimal-light
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - README_zh_Hans.md
  - README_zh_Hant.md
  - README_de.md
  - LICENSE
  - minimal-light.gemspec
  - html_source_file/
